### ISSUE TITLE
JsonPair.value has leading blank

### ISSUE THREAD

**Issue by tbeu** [bsapundzhiev/bsxml-json#6] opened 2015-04-30 20:00 UTC
When asking for the value of key "k" at the node "gain" function JsonNode_getPairValue (of #4) returns " 2" instead of "2". Please note the leading blank. Is this by design?

``` json
{
  "set1": {
    "gain": { "k": "2" },
    "clock": { "offset": "0.1" }
  }
}
```

**Comment by bsapundzhiev** [comment] 2015-05-01 09:21
Its by design because json parser is very basic but is definitely a bug. parser should be fixed

**Comment by tbeu** [comment] 2015-05-02 07:09
It is OK if value is converted to int/float number, but it's not OK if actual string content is used. Thus seeing this fixed would be of help. Thank you.

**Closed as completed** 2015-05-02 13:58 UTC

**Comment by bsapundzhiev** [comment] 2015-05-02 14:00
It's fixed, can you retest the issue.

**Comment by tbeu** [comment] 2015-05-02 18:11
Thanks. Fix confirmed.
